### ISSUE TITLE
Android app crash while share website URL

### ISSUE THREAD

**Issue by vc-rakesh** [calvinckho/capacitor-share-extension#2]
2022-06-08 20:45:02.580 17367-17511/com.ionic.app E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.ionic.app, PID: 17367
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:607)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:257)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:598)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:257) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
        at com.getcapacitor.FileUtils.getFileUrlForUri(FileUtils.java:126)
        at com.getcapacitor.FileUtils.getPortablePath(FileUtils.java:63)
        at com.capacitor.shareextension.plugin.ShareExtension.readItemAt(ShareExtension.java:86)
        at com.capacitor.shareextension.plugin.ShareExtension.checkSendIntentReceived(ShareExtension.java:40)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:598) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:257) 
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by calvinckho** [comment]
please try the latest Capacitor 2, 3, and 4 versions. If the problem persists, I can reopen the issue.
